#!/usr/bin/env bash
# Render the per-customer Caddyfile.
# Reads customer.env (sourced from /etc/wcn-cloud/customer.env or via stdin/args).
# Output: stdout = Caddyfile content.
#
# Usage:
#   render-caddyfile.sh /etc/wcn-cloud/customer.env [extra-domain ...]
#
# Extra domains passed as arguments are added as additional site blocks
# proxying to the same Coolify backend (used when adding custom domains).

source "$(dirname "$0")/common.sh"

env_file="${1:?Usage: $0 <customer.env> [extra domain ...]}"
shift
extra_domains=("$@")

[[ -f "$env_file" ]] || die "customer.env not found at $env_file"
# shellcheck source=/dev/null
source "$env_file"

require_var() {
  local v="$1"
  [[ -n "${!v:-}" ]] || die "Missing $v in $env_file"
}
for v in SLUG CONSOLE_HOSTNAME TIER; do require_var "$v"; done

# Coolify dashboard path = /coolify, Supabase Studio path = /supabase.
# Caddy strips the prefix and passes to the upstream service.
#
# Auth: every protected path runs `forward_auth` against the WCN console's
# /api/verify endpoint. The console issues a signed cookie on successful
# login at https://console.western-communication.com and that cookie is
# scoped to *.western-communication.com so it's sent on this host too.

WCN_VERIFY="${WCN_VERIFY:-https://console.western-communication.com}"

cat <<CADDY
# Auto-generated by render-caddyfile.sh — do not edit by hand.
# Customer: ${SLUG}  (tier: ${TIER})

{
  # global options
  admin localhost:2019
  email cloud-support@western-communication.com
}

# Reusable forward_auth snippet: validates the wcn-fa cookie via the console.
# The console's /api/verify decides allow/deny based on the customer slug
# parsed from X-Forwarded-Host, so we MUST forward the original host.
(wcn_auth) {
    forward_auth ${WCN_VERIFY} {
        uri /api/verify
        header_up X-Forwarded-Host {host}
        copy_headers X-Wcn-User-Id X-Wcn-Role X-Wcn-Customer-Slug
    }
}

# Console host (served via Cloudflare Tunnel — origin sees plain HTTP)
http://${CONSOLE_HOSTNAME} {
    encode gzip

    # —— /coolify : Coolify UI + API ——
    handle_path /coolify/* {
        import wcn_auth
        reverse_proxy http://127.0.0.1:8000 {
            header_up X-Forwarded-Prefix /coolify
        }
    }

    # —— /supabase : Supabase Studio (only if tier has DB) ——
CADDY

if [[ "$SUPABASE_PRESET" != "none" ]]; then
cat <<CADDY
    handle_path /supabase/* {
        import wcn_auth
        reverse_proxy http://127.0.0.1:3000 {
            header_up X-Forwarded-Prefix /supabase
        }
    }

    # —— /api : Supabase Kong (PostgREST, Auth, Storage) ——
    # No forward_auth here — callers authenticate with the Supabase anon
    # or service-role key, which Kong validates.
    handle_path /api/* {
        reverse_proxy http://127.0.0.1:8001
    }
CADDY
else
cat <<CADDY
    # supabase paths disabled — tier=${TIER} has no DB
    handle_path /supabase/* { respond "Not available on your plan" 404 }
    handle_path /api/* { respond "Not available on your plan" 404 }
CADDY
fi

cat <<CADDY

    # —— branding overlay (CSS injection for the Coolify UI) ——
    handle_path /assets/wcn-overlay.css {
        root * /etc/wcn-cloud/branding
        rewrite * /overlay.css
        file_server
    }

    # —— /healthz (used by external monitoring) ——
    respond /healthz "ok" 200

    # —— Catch-all: app workloads (Coolify-managed) get routed by their Host header to Traefik ——
    handle {
        reverse_proxy http://127.0.0.1:8080
    }

    log {
        output file /var/log/caddy/access.log
        format json
    }
}
CADDY

# Per-domain blocks for any custom hostnames the customer's added.
for d in "${extra_domains[@]}"; do
  cat <<CADDY

# Custom domain
http://${d} {
    encode gzip
    reverse_proxy http://127.0.0.1:8080
    log {
        output file /var/log/caddy/${d//[^a-z0-9]/_}.log
        format json
    }
}
CADDY
done
