#!/usr/bin/env bash
# Render the per-customer Caddyfile.
# Reads customer.env (sourced from /etc/wcn-cloud/customer.env or via stdin/args).
# Output: stdout = Caddyfile content.
#
# Usage:
#   render-caddyfile.sh /etc/wcn-cloud/customer.env [extra-domain ...]
#
# Extra domains passed as arguments are added as additional site blocks
# proxying to the same Coolify backend (used when adding custom domains).

source "$(dirname "$0")/common.sh"

env_file="${1:?Usage: $0 <customer.env> [extra domain ...]}"
shift
extra_domains=("$@")

[[ -f "$env_file" ]] || die "customer.env not found at $env_file"
# shellcheck source=/dev/null
source "$env_file"

require_var() {
  local v="$1"
  [[ -n "${!v:-}" ]] || die "Missing $v in $env_file"
}
for v in SLUG CONSOLE_HOSTNAME TIER; do require_var "$v"; done

# ── Domain layout ─────────────────────────────────────────────────────
# Each upstream gets its own subdomain so it can serve from root path —
# Coolify (Laravel), Studio (Next.js) and Kong all generate root-anchored
# URLs/redirects/assets that don't honour X-Forwarded-Prefix. Cookies stay
# scoped to .western-communication.com so console SSO covers all four.
COOLIFY_HOSTNAME="coolify.${CONSOLE_HOSTNAME}"
STUDIO_HOSTNAME="studio.${CONSOLE_HOSTNAME}"
API_HOSTNAME="api.${CONSOLE_HOSTNAME}"

# Auth: every protected host runs `forward_auth` against the WCN console's
# /api/verify endpoint. The console issues a signed cookie on successful
# login at https://console.western-communication.com and that cookie is
# scoped to *.western-communication.com so it's sent on all four hosts.
WCN_VERIFY="${WCN_VERIFY:-https://console.western-communication.com}"

cat <<CADDY
# Auto-generated by render-caddyfile.sh — do not edit by hand.
# Customer: ${SLUG}  (tier: ${TIER})

{
  # global options
  admin localhost:2019
  email cloud-support@western-communication.com
}

# Reusable forward_auth snippet: validates the wcn-fa cookie via the console.
# X-Wcn-Slug is sent explicitly so /api/verify doesn't have to parse the slug
# out of X-Forwarded-Host (which may now be coolify.SLUG.*, studio.SLUG.*, …).
(wcn_auth) {
    forward_auth ${WCN_VERIFY} {
        uri /api/verify
        header_up X-Forwarded-Host {host}
        header_up X-Wcn-Slug ${SLUG}
        copy_headers X-Wcn-User-Id X-Wcn-Role X-Wcn-Customer-Slug
    }
}

# ── Customer app workloads (Coolify-managed, Host-header routed) ──────
http://${CONSOLE_HOSTNAME} {
    encode gzip

    # —— branding overlay (CSS injection for the Coolify UI) ——
    handle_path /assets/wcn-overlay.css {
        root * /etc/wcn-cloud/branding
        rewrite * /overlay.css
        file_server
    }

    # —— /healthz (used by external monitoring) ——
    handle /healthz {
        respond "ok" 200
    }

    # —— Catch-all → Traefik. Port 8081 matches the proxy compose binding
    #     (127.0.0.1:8081:80 — see /data/coolify/proxy/docker-compose.yml).
    handle {
        reverse_proxy http://127.0.0.1:8081
    }

    log {
        output file /var/log/caddy/access.log
        format json
    }
}

# ── Coolify dashboard ─────────────────────────────────────────────────
http://${COOLIFY_HOSTNAME} {
    encode gzip
    import wcn_auth
    reverse_proxy http://127.0.0.1:8000
    log {
        output file /var/log/caddy/access.log
        format json
    }
}
CADDY

if [[ "$SUPABASE_PRESET" != "none" ]]; then
cat <<CADDY

# ── Supabase Studio ───────────────────────────────────────────────────
http://${STUDIO_HOSTNAME} {
    encode gzip
    import wcn_auth
    reverse_proxy http://127.0.0.1:3000
    log {
        output file /var/log/caddy/access.log
        format json
    }
}

# ── Supabase Kong (API) ───────────────────────────────────────────────
# No wcn_auth — Kong validates the anon/service-role JWT itself.
http://${API_HOSTNAME} {
    encode gzip
    reverse_proxy http://127.0.0.1:8001
    log {
        output file /var/log/caddy/access.log
        format json
    }
}
CADDY
else
cat <<CADDY

# studio.* and api.* disabled — tier=${TIER} has no DB.
http://${STUDIO_HOSTNAME} {
    respond "Not available on your plan" 404
}
http://${API_HOSTNAME} {
    respond "Not available on your plan" 404
}
CADDY
fi

# Per-domain blocks for any custom hostnames the customer's added.
for d in "${extra_domains[@]}"; do
  cat <<CADDY

# Custom domain
http://${d} {
    encode gzip
    reverse_proxy http://127.0.0.1:8081
    log {
        output file /var/log/caddy/${d//[^a-z0-9]/_}.log
        format json
    }
}
CADDY
done
